name: Release 🧠 Synapse 💪

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Grant execute permissions to gradlew
        run: chmod +x gradlew
      - name: Build & Test
        run: ./gradlew shadowJar test --no-daemon
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            synapse-core/build/libs/*.jar
            synapse-platform/**/build/libs/synapse-*.jar
